version: 1.0.{build}

branches:
  only:
    - master

skip_tags: true

max_jobs: 1

image: Visual Studio 2017

platform:
  - x86
  - x64

configuration:
  - Release
  - Debug

install:
  - mkdir c:\yasm
  - set PATH=%APPDATA%\npm;c:\yasm;%PATH%
  - set CI=true
  - if "%PLATFORM%" == "x64" curl -o "c:\yasm\yasm.exe" http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe
  - if "%PLATFORM%" == "x86" curl -o "c:\yasm\yasm.exe" http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win32.exe
  - yasm --version

matrix:
  fast_finish: true

build:
  parallel: true
  project: aspia-remote-desktop.sln
  verbosity: detailed

clone_depth: 1